### ISSUE TITLE
RAD-150 Expected Actions uncertainty

### ISSUE THREAD

**Issue by lynnfel** [IHE/RAD.IRA#17]
**Section Number** http://build.fhir.org/ig/IHE/RAD.IRA/branches/april-public-comment-resolution/rad-150.html#24150413-expected-actions

**Issue** In RAD-150 (Update Report Context), the Content Creator is the Sender and the Hub is the Manager Role.
Following our pattern, the Expected Actions of the Request message in 4:150.4.1.3 (copied below) apply to the Hub.   ...but the text in the section applies to the actors who the Hub will route the request to, not to the Hub itself (i.e. the Hub will never "apply updates" to anything).   All the Hub does is RAD-154 to distribute the update, right?

  -  If the context.versionId in the request does not match the version ID of the report anchor context, then the Manager will not apply any updates.
  -  The Manager will apply the set of updates in the request atomically. i.e. The Manager will apply all updates or none of the updates.
  -  If the Manager successfully applies all updates in the request, it will assign a new version ID to the report anchor context.

**Proposed Change** Discuss with RAD Tech.   I have to think about this before making a recommendation...  (Did we already discuss this??)

Depending on whether we make a change to RAD-150 expected actions, then we should also review RAD-151 expected actions (request) to see if a similar update is needed,

**Priority**:

- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by kinsonho** [comment]
@lynnfel The Manager (i.e. the Hub) has to maintain all the updated contents generically as well so that later when it handles a Get Current Context query, it can include the latest contents in the response.

Since the Manager does not have specific business logic as a Subscriber, all the Manager needs to be is to apply the content update request 'generically' in the sense that it will blindly apply the create, update, delete operation to each resource in the request. Then once it manages to apply all changes without problem, then it will forward the event with a new version ID to all applicable subscribers.

**Comment by kinsonho** [comment]
Clarify Hub requirements upon receiving *-update events.
